document.writeln("    <div class=\'navi\'>");
document.writeln("        <div class=\'navi-logo\'>");
document.writeln("            <p><b>jbji\'s Zone</b></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'navi-item\'>");
document.writeln("            <p><a href=\'/index.html\'> Home </a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'navi-item\'>");
document.writeln("            <p><a href=\'/articles/articles.html\'> Articles </a></p>");
document.writeln("            <div class=\'navi-dropdown\'>");
document.writeln("                <a href=\'#\'> Articles </a>");
document.writeln("                <a href=\'#\'> Articles </a>");
document.writeln("                <a href=\'#\'> Articles </a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'navi-item\'>");
document.writeln("            <p><a href=\'/articles/onlinetest.asp\'> Online Test </a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'navi-item\'>");
document.writeln("            <p><a href=\'/aboutme/aboutme.html\'> About Me </a></p>");
document.writeln("        </div>");
document.writeln("        <div class=\'navi-search\'>");
document.writeln("            <form class=\'navi-input\'>");
document.writeln("                <input type =\'text\' name=\'txtSearchItem\' placeholder=\'Type Something...\' />");
document.writeln("                <input type = \'submit\' value=\'Search\'/>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("    </div>");